UMC-NOOK/Client

src/views/auth/sign-in/page/complete.tsx

✨ feat: test

---

src/components/header/Profile.tsx
src/views/library/components/library-items/GridView.tsx
src/views/library/components/library-items/grid-items/SaveList.tsx
src/views/library/components/library-items/grid-items/SaveListItem.tsx
src/views/library/components/library-items/grid-items/SaveListView.tsx
src/views/library/components/library-items/list-items/book-list/BookItem.tsx
src/views/library/components/library-items/list-items/book-list/bookitem-items/DeleteBtn.tsx
src/views/library/components/library-items/list-items/book-list/bookitem-items/InfoBtn.tsx
src/views/library/components/library-items/list-items/book-list/bookitem-items/RecordBtn.tsx
src/views/library/components/library-items/list-items/book-list/bookitem-items/StarMaker.tsx
src/views/library/components/library-items/list-items/filterbar-items/DropDownBar.tsx

- close #47 
- 전반적인 서재 UI 수정했습니다

🎨 Design: 서재 UI 디자인 수정

---

src/utils/layout.ts

🐛 fix: 레이아웃 파일 수정

---

src/utils/layout.ts

- close #69 
- 레이아웃 헤더바 숨기는 함수 로직 수정했습니다

🐛 Fix: hieHeader() 수정

---

src/apis/instance.ts

- close #107 
- 임시로 계속 세션 만료창이 뜨는 문제 해결했습니다. 온전한 방법은 아니라 추후 마저 수정하겠습니다.

🚑 Hotfix: 무한 토큰 재발급 오류 해결

---

src/apis/instance.ts
src/assets/readingRoom/controll-icon/middleUnion.svg
src/store/private-reading-room/useSoundStore.tsx
src/views/library/components/library-items/grid-items/SaveListView.tsx
src/views/reading-room/components/private-reading-room/control-bar/ControlBar.tsx
src/views/reading-room/components/private-reading-room/control-bar/SmallControlBar.tsx
src/views/reading-room/components/private-reading-room/nooki/NookiCharacter.tsx
src/views/reading-room/components/private-reading-room/speech-bubble/SpeechBubble.tsx
src/views/reading-room/components/private-reading-room/speech-bubble/SpeechBubble2.tsx
src/views/reading-room/components/private-reading-room/speech-bubble/SpeechBubble3.tsx
src/views/reading-room/components/private-reading-room/speech-bubble/SpeechBubble4.tsx
src/views/reading-room/hooks/private-reading-room/audio/useAudio.tsx
src/views/reading-room/page/private-reading-room/index.tsx

- close #106 
- 테마에 맞는 음원파일이 재생됩니다. 전체 배경음악 설정 기능을 제거했습니다.
노션으로 첨부하겠습니다

✨ Feat: 리딩룸 음원 파일 연동

---

package-lock.json
package.json
src/views/lounge/apis/lounge/lounge-book/LoungeBookListGet.ts
src/views/lounge/components/lounge/BookCard.tsx
src/views/lounge/components/lounge/BookListSection.tsx
src/views/lounge/components/lounge/CategorySectionView.tsx
src/views/lounge/components/lounge/RecommendView.tsx
src/views/lounge/components/lounge/TapFilter.tsx
src/views/lounge/hooks/useQuery/lounge/useGetLoungeBook.ts

- close #116 
- 책 상세보기 라우터 추가
- 추천 도서 페이지 마진 늘리기

♻️  Refactor : 책 상세보기 라우터 추가

---

src/App.tsx
src/views/library/apis/library/book/bookFetchState.ts
src/views/library/components/library-items/VerticalView.tsx
src/views/library/components/library-items/list-items/book-list/BookItem.tsx
src/views/library/components/library-items/list-items/pagenation/Pagination.tsx
src/views/library/hooks/useQuery/library-query/useGetBookState.ts

Refactor/woojo230 library#120

---

src/routes/router.tsx
src/views/auth/components/LoginOptions.tsx
src/views/library/components/library-items/topbar/TopBar.tsx
src/views/library/page/index.tsx

- close #131 
- 회원가입 텍스트 클릭시 회원가입 페이지로 이동합니다

✨ Feat: 회원가입 라우터 연결

---

src/views/lounge/components/book-info/bestBook.tsx
src/views/lounge/components/book-info/comment.tsx
src/views/lounge/components/book-info/libraryRegistration.tsx
src/views/lounge/hooks/useMutation/book-info-mutation/usePostBookRegistration.ts

🐞 Bug: 독서정보 api 연결 버그 수정

---

src/types/auth/signup/userType.ts
src/views/auth/sign-up/page/index.tsx

- close #139 
- 회원가입 request body 수정

🚑 Hotfix: 회원가입 request body 수정

---

src/views/auth/schemas/sign-in/validateSignIn.ts

- close #146 
- 로그인 비밀번호 검증로직 8자 -> 7자 수정

🐛 Fix: 로그인 검증 로직 수정

---

src/views/lounge/components/lounge/RecommendView.tsx

- close #143
라운지 내에서 닉네임을 불러오는 부분 API 연동을 진행하였습니다.

✨ Feat: 라운지 Api 연동

---

src/components/search/SearchResultList.tsx
src/views/home/components/MiddleNookie.tsx
src/views/home/page/DesignPage.tsx
src/views/library/components/library-items/topbar/TopBar.tsx
src/views/library/page/index.tsx

- close #149 
서재 이름 API 연동 작업 & 누키 꾸미기 벽지 수정 & 검색 페이지네이션 수정

♻️ Refactor: 서재 이름 API 연동

---

src/styles/globals.css
src/views/reading-room/apis/private-reading-room/roomInfoPatch.ts
src/views/reading-room/hooks/private-reading-room/useMutation/usePatchRoomInfo.ts
src/views/reading-room/page/private-reading-room/index.tsx

✨ Feat: 리딩룸 정보 수정 api 연결

---

src/components/header/Profile.tsx
src/views/auth/sign-up/page/index.tsx

- close #150 
- 헤더바 디자인 수정
- 이용약관 url 연결

✨ Feat: 이용약관방침 url 연결

---

src/views/reading-room/apis/reading-room/CreateReadingRoom.ts
src/views/reading-room/apis/reading-room/types/create-reading-room-types.ts
src/views/reading-room/components/reading-room/ActionButtons.tsx
src/views/reading-room/components/views/CreateReadingRoom.tsx
src/views/reading-room/hooks/reading-room/useMutation/useCreateReadingRoom.ts
src/views/reading-room/utils/reading-room/normalize.ts

- close #164 
- 리딩룸 생성하기 API 연동 구

✨ Feat: 리딩룸 생성하기 API 연동 

---

src/components/header/Profile.tsx
src/views/home/components/RegisteredBooksCalendarBox.tsx

- close #175 
디자인 QA 사항을 추가적으로 반영하였습니다.

🎨 Design: 디자인 QA 반영

---

src/views/library/components/library-items/list-items/pagenation/Pagination.tsx

- close #201 
- 서재 페이지 네이션 수정했습니다

🐛 Fix: 서재 페이지네이션 수정

---

src/views/reading-room/components/views/ReadingRoomList.tsx

♻️  Refactor: 페이지네이션 UI 수정

---

src/views/home/apis/reading.ts
src/views/home/components/Booksummary.tsx
src/views/home/components/CurrentlyReadingBox.tsx
src/views/home/components/RecentJournalBox.tsx
src/views/home/components/RecentReadingRoomBox.tsx
src/views/home/hooks/useQuery/useGetHomeReading.ts
src/views/home/hooks/useQuery/useGetHomeRecent.ts

fix: QA 진행 및 홈  오류 수정
